[package]
name = "rust-rectangles"
version = "0.1.0"
authors = ["David Peach <mail@davidpeach.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
